<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<DebugType>full</DebugType>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="ndo.dll" Version="6.0.0" />
	</ItemGroup>

	<Target Name="CustomAfterBuild" AfterTargets="Build" >
		<Exec WorkingDirectory="bin\Debug\net10.0" Command="..\..\..\..\..\NDOEnhancer\NDOEnhancer\bin\debug\net11.0\NDOEnhancer ..\..\..\PureBusinessClasses.ndoproj $(TargetFramework)" />
		<Copy SourceFiles="obj\Debug\net10.0\ndotemp\PureBusinessClasses.dll" DestinationFolder="bin\Debug\net10.0" />
	</Target>

</Project>

 