<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="SourceRevisionId.props" Condition="Exists('SourceRevisionId.props')" />
	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0;net11.0</TargetFrameworks>
		<Version>6.0.0</Version>
		<Authors>Mirko Matytschak</Authors>
		<Company>Mirko Matytschak</Company>
		<Product>.NET Data Objects (NDO)</Product>
		<Copyright>Copyright (c) 2002-2025 Mirko Matytschak, Velden, Germany</Copyright>
		<PackageProjectUrl>https://www.netdataobjects.de</PackageProjectUrl>
		<RepositoryUrl>https://github.com/mirkomaty/NDO</RepositoryUrl>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>ndo.postgre</PackageId>
		<PackageReleaseNotes>Upgrade to NDO 5.0</PackageReleaseNotes>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<AssemblyVersion>6.0.0.0</AssemblyVersion>
		<FileVersion>6.0.0.0</FileVersion>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\NDOInterfaces\NDOInterfaces.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="npgsql" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
		<None Include="readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>