// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NDOVsPackage
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string NDOPackageString = "9a3bfde0-3b01-4a99-9ddc-1544345635fc";
        public static Guid NDOPackage = new Guid(NDOPackageString);

        public const string guidNDOPackageCmdSetString = "7bf3372d-80b5-47ce-8104-704a904fcb3e";
        public static Guid guidNDOPackageCmdSet = new Guid(guidNDOPackageCmdSetString);

        public const string guidImagesString = "1c2bee68-81ce-4f37-bb4f-6460b14e8ed8";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NDOMenuGroup = 0x1020;
        public const int cmdidNDOConfiguration = 0x0100;
        public const int cmdidAddRelation = 0x0101;
        public const int cmdidAddAccessor = 0x0102;
        public const int cmdidAddClass = 0x0103;
        public const int cmdidOpenMappingTool = 0x0104;
        public const int cmdidOpenClassGenerator = 0x0105;
        public const int NDOToolbar = 0x1000;
        public const int bmpConfiguration = 0x0001;
        public const int bmpAddRelation = 0x0002;
        public const int bmpAddAccessor = 0x0003;
        public const int bmpAddClass = 0x0004;
        public const int bmpOpenMappingTool = 0x0005;
        public const int bmpOpenClassGenerator = 0x0006;
    }
}